// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9WpXdMDk-DedrXWVqCGF1bUqRHv746Gw',
    appId: '1:949525009723:web:607ef2dccd0395d2aa531e',
    messagingSenderId: '949525009723',
    projectId: 'todo-f1bdb',
    authDomain: 'todo-f1bdb.firebaseapp.com',
    storageBucket: 'todo-f1bdb.appspot.com',
    measurementId: 'G-NTPY7KW7D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRh1ndQTLIz_9zSIFThuMuXw58m0GcQBc',
    appId: '1:949525009723:android:b6d736eb9f9538f9aa531e',
    messagingSenderId: '949525009723',
    projectId: 'todo-f1bdb',
    storageBucket: 'todo-f1bdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrucloUJM7sohwqc9Iu0wh5Sm06-64pvE',
    appId: '1:949525009723:ios:7b38c41495bdaf18aa531e',
    messagingSenderId: '949525009723',
    projectId: 'todo-f1bdb',
    storageBucket: 'todo-f1bdb.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrucloUJM7sohwqc9Iu0wh5Sm06-64pvE',
    appId: '1:949525009723:ios:7b38c41495bdaf18aa531e',
    messagingSenderId: '949525009723',
    projectId: 'todo-f1bdb',
    storageBucket: 'todo-f1bdb.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9WpXdMDk-DedrXWVqCGF1bUqRHv746Gw',
    appId: '1:949525009723:web:da8bc3ad14a0e8afaa531e',
    messagingSenderId: '949525009723',
    projectId: 'todo-f1bdb',
    authDomain: 'todo-f1bdb.firebaseapp.com',
    storageBucket: 'todo-f1bdb.appspot.com',
    measurementId: 'G-7NTHXTDZG5',
  );
}
